### ISSUE TITLE
typing_extensions incompatibility with Python 3.6?

### ISSUE THREAD

**Issue by tmccc** [JonnyWong16/plexpy#1949]
### Describe the Bug

Getting the following error after a recent Tautulli upgrade - using Python 3.6 on Ubuntu 18.04:

```
● tautulli.service - Tautulli - Stats for Plex Media Server usage
   Loaded: loaded (/lib/systemd/system/tautulli.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2022-12-28 04:20:30 GMT; 8s ago
  Process: 29160 ExecStart=/usr/bin/python3 /data/Tautulli/Tautulli.py --config /data/Tautulli/config.ini --datadir /data/Tautulli --qui
 Main PID: 29160 (code=exited, status=1/FAILURE)

Dec 28 04:20:30 big-nas-2 python3[29160]:     from arrow import formatter, locales, parser, util
Dec 28 04:20:30 big-nas-2 python3[29160]:   File "/data/Tautulli/lib/arrow/formatter.py", line 10, in <module>
Dec 28 04:20:30 big-nas-2 python3[29160]:     from arrow import locales
Dec 28 04:20:30 big-nas-2 python3[29160]:   File "/data/Tautulli/lib/arrow/locales.py", line 20, in <module>
Dec 28 04:20:30 big-nas-2 python3[29160]:     from typing_extensions import Literal
Dec 28 04:20:30 big-nas-2 python3[29160]:   File "/data/Tautulli/lib/typing_extensions.py", line 193, in <module>
Dec 28 04:20:30 big-nas-2 python3[29160]:     class _FinalForm(typing._SpecialForm, _root=True):
Dec 28 04:20:30 big-nas-2 python3[29160]: AttributeError: module 'typing' has no attribute '_SpecialForm'
Dec 28 04:20:30 big-nas-2 systemd[1]: tautulli.service: Main process exited, code=exited, status=1/FAILURE
Dec 28 04:20:30 big-nas-2 systemd[1]: tautulli.service: Failed with result 'exit-code'.
```
A quick google implies that typing_extensions is now using a feature from Python 3.7, whereas Ubuntu 18.04 still uses 3.6.

### Steps to Reproduce

Upgrade to the latest Tautulli via git pull on a linux installation using Python 3.6.

### Expected Behavior

Probably should still work using Python 3.6? 

### Tautulli Version

v2.11.1

### Git Branch

master

### Git Commit Hash

Unknown

### Platform and Version

Ubuntu 18.04.6

### Python Version

3.6.9

### Browser and Version

Safari  16.1

### Link to Logs

N/A

**Comment by danozdotnet** [comment]
Same with CentOS 8 Stream, Python 3.6.8

**Comment by JonnyWong16** [comment]
Duplicate #1946.
