### ISSUE TITLE
Doesn't work with python 3.10 -- import collectors is removed in 3.10

### ISSUE THREAD

**Issue by jvasa** [JonnyWong16/plexpy#1558]
### Describe the Bug

https://github.com/Tautulli/Tautulli/blob/master/lib/urllib3/util/selectors.py uses
Line 14:
from collections import namedtuple, Mapping
gives error in 3.10
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections'

Since python 3.3 it shows the deprecated warning, now is removed.

### Steps to Reproduce

How to reproduce. Simply run:
In 3.8: Shows Warning

Python 3.8.12 (default, Aug 30 2021, 00:00:00) 
[GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> from collections import namedtuple, Mapping
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
\>\>\> 

In 3.10 (which is now default on Fedora 35) gives error:
Python 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> from collections import namedtuple, Mapping
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
\>\>\> 

### Expected Behavior

Expected to import in 3.10. Tautulli will not work in 3.10 from what I see.

### Screenshots

see log

### Relevant Settings

See log

### Tautulli Version

Latest

### Git Branch

master

### Git Commit Hash

5f22ad26ad52fbf7881aac988a59853a2bde9887

### Platform and Version

Fedora 35

### Python Version

3.1.10

### Browser and Version

Latest Chrome

### Link to Logs

https://gist.github.com/jvasa/86a827711186b44c622a1bf91b0ff92b

**Comment by jvasa** [comment]
I thought my incorrect startup scripts were the cause, but I download the latest and tried it again and see same error:
\# python3 --version
Python 3.10.0
\# /usr/bin/python3 /opt/Tautulli/Tautulli.py --config /opt/Tautulli/config.ini --datadir /opt/Tautulli 
Traceback (most recent call last):
  File "/opt/Tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/opt/Tautulli/plexpy/__init__.py", line 67, in <module>
    from plexpy import activity_handler
  File "/opt/Tautulli/plexpy/activity_handler.py", line 37, in <module>
    from plexpy import activity_processor
  File "/opt/Tautulli/plexpy/activity_processor.py", line 32, in <module>
    from plexpy import database
  File "/opt/Tautulli/plexpy/database.py", line 31, in <module>
    from plexpy import helpers
  File "/opt/Tautulli/plexpy/helpers.py", line 26, in <module>
    import cloudinary
  File "/opt/Tautulli/lib/cloudinary/__init__.py", line 18, in <module>
    from cloudinary import utils
  File "/opt/Tautulli/lib/cloudinary/utils.py", line 18, in <module>
    from urllib3 import ProxyManager, PoolManager
  File "/opt/Tautulli/lib/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/opt/Tautulli/lib/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/opt/Tautulli/lib/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/opt/Tautulli/lib/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/opt/Tautulli/lib/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/opt/Tautulli/lib/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/opt/Tautulli/lib/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)

**Comment by jvasa** [comment]
Please reopen @JonnyWong16

**Comment by jvasa** [comment]
I shouldn't of asked to close this.

**Comment by JonnyWong16** [comment]
Nope, remaining closed because it's a duplicate of #1522.
